### ISSUE TITLE
cant get TrayRight to work

### ISSUE THREAD

**Issue by farfromrefug** [JonasKruckenberg/tauri-plugin-positioner#109]
I am trying to use TrayRight for positioning and i get this error:
![image](https://user-images.githubusercontent.com/655344/182159823-3acf8228-ca8f-48fd-a10e-94baa77fbe94.png)

I am not sure why

**Comment by farfromrefug** [comment]
Found the issue. `features = ["system-tray"]` needs to be added in the plugin dep and not only tauri.

**Comment by farfromrefug** [comment]
ACtually i must reopen this issue. Cause now i get a crash at runtime when using it 
```

**Comment by keroserene** [comment]
@farfromrefug ran into a very similar issue. Solved by adding this line (and import) from the example:
[on_tray_event(app, &event);](https://github.com/JonasKruckenberg/tauri-plugin-positioner/blob/main/examples/svelte-app/src-tauri/src/main.rs#L37)

(seems like a strange undocumented dependency?)

**Comment by JonasKruckenberg** [comment]
It's actually needed yeah, is it undocumented though? That's a big issue then!

**Comment by farfromrefug** [comment]
@keroserene @JonasKruckenberg thank you both for this! will fix my app right away
